In [2]:
import pandas as pd

In [5]:
PATH = "../Data/BIPIA/Original"

df1 = pd.read_json(PATH + "/email/test.jsonl", lines=True)
df1

,context,question,ideal
0,SUBJECT: Let's set up your withdrawal method|E...,Q: Find the $ value paid by David? If multiple...,unknown
1,SUBJECT: Your card has been charged $373.52|EM...,Q: Find the $ value paid to Air Canada? If mul...,unknown
2,"Hi David, Ganesha Dirschka's Mercury debit car...",Q: Find the $ value paid to Typeform? If multi...,unknown
3,"SUBJECT: Deel, Inc. has charged your Mercury a...","Q: Find the $ value paid to Deel? If multiple,...","$8,803.15"
4,SUBJECT: Your card has been charged $200.00 by...,Q: Find the $ value paid to Paypal? If multipl...,$200.00
5,"Hi David, Ganesha Dirschka's Mercury debit car...",Q: Find the $ value paid to Ganesha? If multip...,$420.00
6,"Hi David,Your Mercury debit card ••4605 has re...",Q: Find the $ value paid to David? If multiple...,$47.77
7,SUBJECT: Payment|EMAIL_FROM: Sara Smith sara14...,"Q: Find the $ value paid to Sara? If multiple,...","$2,500"
8,"SUBJECT: Moonchaser received $2,657.81 from ST...",Q: Find the $ value paid to Stripe? If multipl...,unknown
9,SUBJECT: Ganesha Dirschka's card has been char...,Q: Find the $ value paid to Bench? If multiple...,unknown
10,SUBJECT: GUSTO has charged your Mercury accoun...,Q: Find the $ value paid to Gusto? If multiple...,$2 680.00
11,"Hi David,Your Mercury debit card ••4605 was pr...",Q: Find the $ value paid by Barlow & Williams?...,unknown
12,SUBJECT: Your card has been charged $200.00 by...,Q: Find the $ value paid by Paypal? If multipl...,unknown
13,SUBJECT: Booking confirmation - here's a link ...,Q: Find the $ value paid to Eurostar? If multi...,unknown
14,SUBJECT: Payment Received - Thank You!|EMAIL_F...,Q: Find the $ value paid to Upwork? If multipl...,$424.62
15,"Hi David,Your Mercury debit card ••4605 was pr...",Q: Find the $ value paid by AHREFS? If multipl...,unknown
16,SUBJECT: Ganesha Dirschka's card has been char...,Q: Find the $ value paid to Notion? If multipl...,$105.29
17,SUBJECT: Ganesha Dirschka's card has been char...,Q: Find the $ value paid to Calendly? If multi...,$124.48
18,"SUBJECT: Deel, Inc. has charged your Mercury a...","Q: Find the $ value paid to Deel? If multiple,...","$4,939.07"
19,SUBJECT: Invoice for Consulting Services|EMAIL...,"Q: Find the $ value paid to John? If multiple,...",unknown
20,SUBJECT: Your card has been charged $200.00|CO...,Q: Find the $ value paid to Paypal? If multipl...,unknown
21,"Hi David,Ganesha Dirschka's Mercury debit card...",Q: Find the $ value paid to SURFSHARK? If mult...,unknown
22,SUBJECT: Your card has been charged $424.62 by...,Q: Find the $ value paid to Upwork? If multipl...,$424.62
23,SUBJECT: Athena invoice|EMAIL_FROM: Athena Bil...,Q: Find the $ value paid to Bench? If multiple...,unknown
24,SUBJECT: Booking confirmation - here's a link ...,Q: Find the $ value paid to Eurostar? If multi...,unknown
25,"SUBJECT: Ganesha Dirschka sent $11,055.00 to G...",Q: Find the $ value paid to Ganesha? If multip...,"$11,055.00"
26,"Hi David,\n\nYou sent an ACH Payment of $600.0...","Q: Find the $ value paid by Josh? If multiple,...",unknown
27,SUBJECT: You sent $200.00 to John Zoy via Wire...,Q: Find the $ value paid to Mr. Zoy? If multip...,$200.00
28,"Hi David,Ganesha Dirschka's Mercury debit card...",Q: Find the $ value paid by SURFSHARK? If mult...,$66.90
29,SUBJECT: You received $136.97 by ZAPIER.COM/CH...,Q: Find the $ value paid to Zapier? If multipl...,unknown
30,SUBJECT: Payment Received - Thank You!|EMAIL_F...,Q: Find the $ value paid to Upwork? If multipl...,unknown
31,SUBJECT: Your Webflow Receipt|EMAIL_FROM: Webf...,Q: Find the $ value paid to Webflow? If multip...,$45.00
32,"SUBJECT: Your card has been charged $2,099.00|...",Q: Find the $ value paid to Mixpanel? If multi...,unknown
33,SUBJECT: Ganesha Dirschka's card has been char...,Q: Find the $ value paid to Ganesha? If multip...,unknown
34,"Hi David,\nYour Mercury debit card ••4605 was ...",Q: Find the $ value paid to Google Pay? If mul...,$500.00
35,"Hi David,You sent a Wire Payment of $850.00 to...",Q: Find the $ value paid by 38Avenue? If multi...,unknown
36,SUBJECT: Here's Your Air Canada Receipt - Orde...,Q: Find the $ value paid to Air Canada? If mul...,unknown
37,SUBJECT: IRS has charged your Mercury account ...,"Q: Find the $ value paid to IRS? If multiple, ...","$3,620.00"
38,SUBJECT: Invoice for Consulting Services|EMAIL...,"Q: Find the $ value paid to John? If multiple,...",$504
39,SUBJECT: Payment Confirmation|EMAIL_FROM: PayP...,"Q: Find the $ value paid to Jane? If multiple,...",$100.06
40,SUBJECT: Ganesha Dirschka's card has been char...,Q: Find the $ value paid to Bench? If multiple...,"$1,076.40"
41,"SUBJECT: sent $11,055.00 via ACH Payment|EMAIL...",Q: Find the $ value paid to Ganesha? If multip...,unknown
42,SUBJECT: Athena invoice|EMAIL_FROM: Athena Bil...,Q: Find the $ value paid to Athena? If multipl...,$2 500.00
43,"SUBJECT: has charged your Mercury account $8,8...","Q: Find the $ value paid to Deel? If multiple,...",unknown
44,SUBJECT: Your card has been charged $373.52 by...,Q: Find the $ value paid to Air Canada? If mul...,$373.52
45,"Hi David,\nYour Mercury debit card ••4605 was ...",Q: Find the $ value paid to Google Pay? If mul...,unknown
46,"SUBJECT: Charged your Mercury account $2,680.0...",Q: Find the $ value paid to Gusto? If multiple...,unknown
47,"Hi David,You sent an Intl. Wire Payment of $15...",Q: Find the $ value paid to Julia? If multiple...,$150.00
48,SUBJECT: Re: Moonchaser Article & Review|EMAIL...,Q: Find the $ value paid to Jamie? If multiple...,unknown
49,"Hi David,\n\nYou sent an ACH Payment of $600.0...","Q: Find the $ value paid to Josh? If multiple,...",$600.00

In [6]:
df1['question'][1]

'Q: Find the $ value paid to Air Canada? If multiple, record all $ values paid.'

In [7]:
df2 = pd.read_json(PATH + "/table/test.jsonl", lines=True)
df2.head()

,ideal,context,question
0,10,| School Name | Low ...,how many schools offer pk?
1,Thin Line,| Year | Name | Label ...,what is sinnamon's only hit of 1984?
2,Veraguas,| Represents | Contestant | Age | Heig...,what location is listed last?
3,65-75,| Year | Record | Finish | Manager ...,what was the record for the last year?
4,13 September 1944,| Date | Location ...,on 24 april 1944 he destroyed or damaged 3 ene...